// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFd68R52v6euJ0hbgOmUZYc1FaUzvV_A8',
    appId: '1:680397691158:web:41aff640410451f7f39837',
    messagingSenderId: '680397691158',
    projectId: 'finalpro-4ed25',
    authDomain: 'finalpro-4ed25.firebaseapp.com',
    storageBucket: 'finalpro-4ed25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bfZa3fh64p6Ej-l7d5WRNgyXlHN-tho',
    appId: '1:680397691158:android:4d80fd329013e7d6f39837',
    messagingSenderId: '680397691158',
    projectId: 'finalpro-4ed25',
    storageBucket: 'finalpro-4ed25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCce2Pg-vsvcjKpiHlawZGsN8fcCsfC5gA',
    appId: '1:680397691158:ios:e035db787e935dcbf39837',
    messagingSenderId: '680397691158',
    projectId: 'finalpro-4ed25',
    storageBucket: 'finalpro-4ed25.appspot.com',
    iosClientId: '680397691158-0cfqojujmk3mc3vrll7ncrl2pfii865m.apps.googleusercontent.com',
    iosBundleId: 'com.example.akhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCce2Pg-vsvcjKpiHlawZGsN8fcCsfC5gA',
    appId: '1:680397691158:ios:e035db787e935dcbf39837',
    messagingSenderId: '680397691158',
    projectId: 'finalpro-4ed25',
    storageBucket: 'finalpro-4ed25.appspot.com',
    iosClientId: '680397691158-0cfqojujmk3mc3vrll7ncrl2pfii865m.apps.googleusercontent.com',
    iosBundleId: 'com.example.akhir',
  );
}
